---
development:
  cloud_name: rudolf-media
  api_key: '247847326997132'
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
  secure: true
production:
  cloud_name: rudolf-media
  api_key: '247847326997132'
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
  secure: true
